/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    services: Service;
    testimonials: Testimonial;
    achievements: Achievement;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    achievements: AchievementsSelect<false> | AchievementsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'home-page': HomePage;
    'about-page': AboutPage;
    'contact-settings': ContactSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-settings': ContactSettingsSelect<false> | ContactSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * User accounts for CMS access and future portal users
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'trainer' | 'user';
  avatar?: (number | null) | Media;
  phone?: string | null;
  /**
   * Future customer portal settings
   */
  portalAccess?: {
    hasPortalAccess?: boolean | null;
    assignedTrainer?: (number | null) | User;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload and manage images and files
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility and SEO
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  /**
   * Brief description for SEO and previews
   */
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sections?:
    | (
        | {
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            image: number | Media;
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            imagePosition?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageTextBlock';
          }
        | {
            heading: string;
            description?: string | null;
            buttonText: string;
            buttonLink: string;
            style?: ('primary' | 'secondary') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  subtitle?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Brief description for service cards
   */
  shortDescription?: string | null;
  image?: (number | null) | Media;
  icon?:
    | ('dumbbell' | 'users' | 'calendar' | 'smartphone' | 'target' | 'trophy' | 'heart' | 'activity' | 'video' | 'star')
    | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  pricing?: {
    showPricing?: boolean | null;
    price?: number | null;
    currency?: string | null;
    period?: ('session' | 'month' | 'package') | null;
  };
  ctaButton?: {
    text?: string | null;
    link?: string | null;
  };
  /**
   * Show this service prominently on homepage
   */
  featured?: boolean | null;
  /**
   * Display order (lower numbers first)
   */
  order?: number | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  /**
   * e.g., "Client for 6 months", "Personal Training Client"
   */
  role?: string | null;
  image?: (number | null) | Media;
  quote: string;
  rating?: number | null;
  serviceUsed?: (number | null) | Service;
  /**
   * Show on homepage
   */
  featured?: boolean | null;
  order?: number | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements".
 */
export interface Achievement {
  id: number;
  title: string;
  description?: string | null;
  year?: number | null;
  category?: ('competition' | 'certification' | 'award' | 'milestone') | null;
  image?: (number | null) | Media;
  icon?: ('trophy' | 'medal' | 'award' | 'certificate' | 'star') | null;
  order?: number | null;
  featured?: boolean | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact form submissions from the website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  service?:
    | ('personal-training' | 'exercise-plans' | 'virtual-classes' | 'group-training' | 'app-training' | 'general')
    | null;
  message: string;
  status: 'new' | 'read' | 'responded' | 'archived';
  /**
   * Internal notes about this submission
   */
  notes?: string | null;
  metadata?: {
    ipAddress?: string | null;
    userAgent?: string | null;
    honeypot?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'achievements';
        value: number | Achievement;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  phone?: T;
  portalAccess?:
    | T
    | {
        hasPortalAccess?: T;
        assignedTrainer?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  sections?:
    | T
    | {
        textBlock?:
          | T
          | {
              heading?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        imageTextBlock?:
          | T
          | {
              image?: T;
              heading?: T;
              content?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              heading?: T;
              description?: T;
              buttonText?: T;
              buttonLink?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  description?: T;
  shortDescription?: T;
  image?: T;
  icon?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        showPricing?: T;
        price?: T;
        currency?: T;
        period?: T;
      };
  ctaButton?:
    | T
    | {
        text?: T;
        link?: T;
      };
  featured?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  image?: T;
  quote?: T;
  rating?: T;
  serviceUsed?: T;
  featured?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements_select".
 */
export interface AchievementsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  year?: T;
  category?: T;
  image?: T;
  icon?: T;
  order?: T;
  featured?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  service?: T;
  message?: T;
  status?: T;
  notes?: T;
  metadata?:
    | T
    | {
        ipAddress?: T;
        userAgent?: T;
        honeypot?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteTagline?: string | null;
  logo?: (number | null) | Media;
  /**
   * Logo for dark backgrounds
   */
  logoDark?: (number | null) | Media;
  favicon?: (number | null) | Media;
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  ogImage?: (number | null) | Media;
  socialLinks?:
    | {
        platform: 'instagram' | 'facebook' | 'tiktok' | 'youtube' | 'twitter' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  announcementBanner?: {
    enabled?: boolean | null;
    message?: string | null;
    link?: string | null;
    linkText?: string | null;
  };
  /**
   * Google Analytics Measurement ID (G-XXXXXXX)
   */
  googleAnalyticsId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        label: string;
        link: string;
        newTab?: boolean | null;
        /**
         * Style as primary CTA button
         */
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  ctaButton?: {
    enabled?: boolean | null;
    text?: string | null;
    link?: string | null;
    style?: ('primary' | 'secondary' | 'whatsapp') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              link: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  schedule?:
    | {
        days: string;
        hours: string;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  legalLinks?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroTitle: string;
  heroSubtitle?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * YouTube or Vimeo embed URL for background video
   */
  heroBackgroundVideo?: string | null;
  heroCta?: {
    primaryButton?: {
      text?: string | null;
      link?: string | null;
    };
    secondaryButton?: {
      enabled?: boolean | null;
      text?: string | null;
      link?: string | null;
    };
  };
  valueProposition?: {
    enabled?: boolean | null;
    heading?: string | null;
    subheading?: string | null;
    highlights?:
      | {
          icon?: ('target' | 'heart' | 'trophy' | 'users' | 'calendar' | 'trending-up') | null;
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  aboutPreview?: {
    enabled?: boolean | null;
    heading?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    ctaText?: string | null;
    ctaLink?: string | null;
  };
  servicesSection?: {
    enabled?: boolean | null;
    heading?: string | null;
    subheading?: string | null;
    showFeaturedOnly?: boolean | null;
    maxServices?: number | null;
    ctaText?: string | null;
    ctaLink?: string | null;
  };
  whyChooseUs?: {
    enabled?: boolean | null;
    heading?: string | null;
    reasons?:
      | {
          icon?: ('check-circle' | 'shield' | 'star' | 'clock' | 'zap' | 'award') | null;
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  achievementsSection?: {
    enabled?: boolean | null;
    heading?: string | null;
    showFeaturedOnly?: boolean | null;
  };
  testimonialsSection?: {
    enabled?: boolean | null;
    heading?: string | null;
    subheading?: string | null;
    showFeaturedOnly?: boolean | null;
    maxTestimonials?: number | null;
  };
  contactCta?: {
    enabled?: boolean | null;
    heading?: string | null;
    subheading?: string | null;
    backgroundImage?: (number | null) | Media;
    primaryButton?: {
      text?: string | null;
      link?: string | null;
    };
    whatsappButton?: {
      enabled?: boolean | null;
      text?: string | null;
    };
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  heroTitle: string;
  heroSubtitle?: string | null;
  heroImage?: (number | null) | Media;
  mainContent?: {
    heading?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
  };
  credentials?: {
    heading?: string | null;
    items?:
      | {
          title: string;
          institution?: string | null;
          year?: number | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  missionValues?: {
    missionHeading?: string | null;
    missionContent?: string | null;
    valuesHeading?: string | null;
    values?:
      | {
          title: string;
          description?: string | null;
          icon?: ('heart' | 'star' | 'shield' | 'users' | 'target' | 'trending-up') | null;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings".
 */
export interface ContactSetting {
  id: number;
  whatsapp: {
    enabled?: boolean | null;
    /**
     * WhatsApp number with country code (no + or spaces)
     */
    phoneNumber: string;
    defaultMessage?: string | null;
    floatingButton?: {
      enabled?: boolean | null;
      position?: ('bottom-right' | 'bottom-left') | null;
      showOnMobile?: boolean | null;
    };
  };
  email: {
    /**
     * Email address to receive contact form submissions
     */
    contactEmail: string;
    notifyOnSubmission?: boolean | null;
    /**
     * Send confirmation email to the person who submitted the form
     */
    sendConfirmation?: boolean | null;
  };
  location?: {
    showMap?: boolean | null;
    address?: string | null;
    /**
     * Google Maps embed URL for the location
     */
    googleMapsUrl?: string | null;
    coordinates?: {
      lat?: number | null;
      lng?: number | null;
    };
  };
  businessHours?: {
    showHours?: boolean | null;
    timezone?: string | null;
    hours?:
      | {
          days: string;
          hours: string;
          closed?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  contactPage?: {
    heroTitle?: string | null;
    heroSubtitle?: string | null;
    formHeading?: string | null;
    successMessage?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteTagline?: T;
  logo?: T;
  logoDark?: T;
  favicon?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  ogImage?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  announcementBanner?:
    | T
    | {
        enabled?: T;
        message?: T;
        link?: T;
        linkText?: T;
      };
  googleAnalyticsId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        link?: T;
        newTab?: T;
        highlight?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        enabled?: T;
        text?: T;
        link?: T;
        style?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              link?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  address?: T;
  phone?: T;
  email?: T;
  schedule?:
    | T
    | {
        days?: T;
        hours?: T;
        id?: T;
      };
  copyrightText?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  heroBackgroundVideo?: T;
  heroCta?:
    | T
    | {
        primaryButton?:
          | T
          | {
              text?: T;
              link?: T;
            };
        secondaryButton?:
          | T
          | {
              enabled?: T;
              text?: T;
              link?: T;
            };
      };
  valueProposition?:
    | T
    | {
        enabled?: T;
        heading?: T;
        subheading?: T;
        highlights?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  aboutPreview?:
    | T
    | {
        enabled?: T;
        heading?: T;
        content?: T;
        image?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        ctaText?: T;
        ctaLink?: T;
      };
  servicesSection?:
    | T
    | {
        enabled?: T;
        heading?: T;
        subheading?: T;
        showFeaturedOnly?: T;
        maxServices?: T;
        ctaText?: T;
        ctaLink?: T;
      };
  whyChooseUs?:
    | T
    | {
        enabled?: T;
        heading?: T;
        reasons?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  achievementsSection?:
    | T
    | {
        enabled?: T;
        heading?: T;
        showFeaturedOnly?: T;
      };
  testimonialsSection?:
    | T
    | {
        enabled?: T;
        heading?: T;
        subheading?: T;
        showFeaturedOnly?: T;
        maxTestimonials?: T;
      };
  contactCta?:
    | T
    | {
        enabled?: T;
        heading?: T;
        subheading?: T;
        backgroundImage?: T;
        primaryButton?:
          | T
          | {
              text?: T;
              link?: T;
            };
        whatsappButton?:
          | T
          | {
              enabled?: T;
              text?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  mainContent?:
    | T
    | {
        heading?: T;
        content?: T;
        image?: T;
      };
  credentials?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              title?: T;
              institution?: T;
              year?: T;
              image?: T;
              id?: T;
            };
      };
  missionValues?:
    | T
    | {
        missionHeading?: T;
        missionContent?: T;
        valuesHeading?: T;
        values?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings_select".
 */
export interface ContactSettingsSelect<T extends boolean = true> {
  whatsapp?:
    | T
    | {
        enabled?: T;
        phoneNumber?: T;
        defaultMessage?: T;
        floatingButton?:
          | T
          | {
              enabled?: T;
              position?: T;
              showOnMobile?: T;
            };
      };
  email?:
    | T
    | {
        contactEmail?: T;
        notifyOnSubmission?: T;
        sendConfirmation?: T;
      };
  location?:
    | T
    | {
        showMap?: T;
        address?: T;
        googleMapsUrl?: T;
        coordinates?:
          | T
          | {
              lat?: T;
              lng?: T;
            };
      };
  businessHours?:
    | T
    | {
        showHours?: T;
        timezone?: T;
        hours?:
          | T
          | {
              days?: T;
              hours?: T;
              closed?: T;
              id?: T;
            };
      };
  contactPage?:
    | T
    | {
        heroTitle?: T;
        heroSubtitle?: T;
        formHeading?: T;
        successMessage?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}